# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: note.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nnote.proto\"\xa5\x01\n\x04Note\x12\n\n\x02id\x18\x01 \x01(\x03\x12\r\n\x05\x66ront\x18\x02 \x01(\t\x12\x0c\n\x04hint\x18\x03 \x01(\t\x12\x0c\n\x04word\x18\x04 \x01(\t\x12\x0c\n\x04\x62\x61\x63k\x18\x05 \x01(\t\x12\x12\n\nextra_info\x18\x06 \x01(\t\x12\x12\n\ncreated_ts\x18\x07 \x01(\x01\x12\x16\n\x0elast_edited_ts\x18\x08 \x01(\x01\x12\x18\n\x10last_exported_ts\x18\t \x01(\x01')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'note_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _NOTE._serialized_start=15
  _NOTE._serialized_end=180
# @@protoc_insertion_point(module_scope)
