# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: reverso.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rreverso.proto\":\n\x07\x45xample\x12\x0e\n\x06polish\x18\x01 \x01(\t\x12\x0f\n\x07\x65nglish\x18\x02 \x01(\t\x12\x0e\n\x06source\x18\x03 \x01(\t\"C\n\x08\x45xamples\x12\x1a\n\x08\x65xamples\x18\x01 \x03(\x0b\x32\x08.Example\x12\x1b\n\x13latest_scraped_page\x18\x02 \x01(\x05')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'reverso_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EXAMPLE._serialized_start=17
  _EXAMPLE._serialized_end=75
  _EXAMPLES._serialized_start=77
  _EXAMPLES._serialized_end=144
# @@protoc_insertion_point(module_scope)
